version: '3.8'

services:
  magento:
    image: adobecommerce/magento:latest
    container_name: magento2
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MAGENTO_USERNAME=admin
      - MAGENTO_PASSWORD=admin123
      - MAGENTO_EMAIL=admin@example.com
      - MAGENTO_BASE_URL=http://localhost
      - MYSQL_HOST=db
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento123
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - magento_data:/var/www/html
    depends_on:
      - db
      - elasticsearch

  db:
    image: mysql:8.0
    container_name: magento2-db
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento123
    volumes:
      - db_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: magento2-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  magento_data:
  db_data:
  elasticsearch_data:
